name: Node CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
 - run: npm run test:cin - run: npm run test:coveragen - name: Upload coverage (lcov)n if: always()n uses: actions/upload-artifact@v4n with:n name: coverage-lcovn path: coverage/lcov.infon if-no-files-found: ignore
